### ISSUE TITLE
[Vue v2.4.3] $refs.topProgress is undefined

### ISSUE THREAD

**Issue by Linzdigr** [dalphyx/vue-top-progress#4]
Since Vue 2.4.3, $refs.topProgress is undefined inspite of its key being defined in the $refs variable.
The strange thing is that it's not immediately undefined (at root's mounted Vue hook, the expected object is present but calling later start or done topProgress's functions results in throwing an error.

Is someone else has the same issue?

**Comment by dalphyx** [comment]
@Linzdigr Vue 2.4.3+ changes some behavior and case this issue. You can refer to [#6632](https://github.com/vuejs/vue/issues/6632).

**Comment by dalphyx** [comment]
Vue 2.5.0 has fix this issue, just upgrade it:)
