### ISSUE TITLE
请问如何使用纯前端来监控一个页面加载到dom渲染结束

### ISSUE THREAD

**Issue by Jiiiiiin** [dalphyx/vue-top-progress#5]
上了这个插件之后，如何实际的根据网页的初始化到页面dom/css/js解析完毕，来真实的反应进度，请问有没有同学考虑过这个问题，或者有最佳实践？

**Comment by dalphyx** [comment]
@Jiiiiiin 由于此组件初始化于vue相关的js加载完成后，所以无法在页面初始化一开始就显示，所以没有办法反应你说要求的真实的进度。事实上此类组件一般多应用于展示数据请求时的loading，偏向于展示数据请求时的进度。

**Comment by Jiiiiiin** [comment]
@dalphyx 理解你的意思，但是这样感觉和组件的业务意义不相符 呵呵，不过还是谢谢提供。我在想单纯反应vue的解析和单个页面数据load的过程 其实也还好，因为我看vux的官网感觉是这样反应的。
