### ISSUE TITLE
[Vue warn]: Error in mounted hook: "TypeError: Cannot read property 'start' of undefined"

### ISSUE THREAD

**Issue by icangku** [dalphyx/vue-top-progress#9]
[Vue warn]: Error in mounted hook: "TypeError: Cannot read property 'start' of undefined"
VueJS 2.x

**Comment by ploissken** [comment]
Im experiencing it too, despite the progress bar behaving normally...

    "vue": "^2.6.10",
    "vue-top-progress": "^0.7.0",


```
<script>
import { vueTopprogress } from 'vue-top-progress'
...
  mounted () {
    this.$refs.topProgress.start() 
...


```
